print("Welcome to the Band Name Generator")
#input("which city did you grow up in?")
city = input("what city did you grow up in?\n")
print(city)
pet=input(" what is the name of a pet?\n")
print("Your brand name should be: " + city+ "" + pet)
 #conbine=(city,pet)
 #print(conbine)
 #print("You band name is "conbine")